[tool.poetry]
name = "formulast_scraper"
description = "Formulast Scraper"
authors = ["Jacob Sampson"]
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
beautifulsoup4 = ">=4.12,<5.0"
lxml = ">5.2,<6.0"
requests = ">2.32,<3.0"
